Repository mitodl/ocw-to-hugo, pull requests merged in 2020-10, with the labels that each got.

#90 Fix missing home page bug
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: waiting on author

#91 Remove unneeded fs commands
  src/aws_sync.js
  src/aws_sync_test.js
  src/file_operations.js
  src/file_operations_test.js
  src/helpers.js
Labels: waiting on author

#94 Fix bug with missing file_location
  src/helpers.js
  src/helpers_test.js
Labels: waiting on author

#97 Fix AWS etag key error
  src/aws_sync.js
  src/aws_sync_test.js
Labels: waiting on author

#92 Move courseUidList to local variable, and flip key and value for performance
  src/file_operations.js
  src/file_operations_test.js
  src/helpers.js
  src/helpers_test.js
  src/markdown_generators.js
Labels: waiting on author

#85 table header rows fix
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: waiting on author

#98 fix a typo in the usage string
  src/bin/index.js
Labels: waiting on author

#99 Exit with non-zero exit code only on verbose, if a non-fatal error occurs
  src/bin/index.js
Labels: needs review

#100 Error if master JSON is missing for a course and the user has a course list
  src/aws_sync_test.js
  src/bin/index.js
  src/file_operations.js
  src/file_operations_test.js
  test_data/courses/intentionally_left_empty.txt
Labels: needs review

#101 Add lastpublished data to course front matter
  package.json
  src/constants.js
  src/markdown_generators.js
  src/markdown_generators_test.js
  yarn.lock
Labels: waiting on author

#103 Handle an empty string for instructors
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: needs review

#104 ocw-to-hugo 1.0.11
  package.json
  src/aws_sync_test.js
  src/bin/index.js
  src/constants.js
  src/file_operations.js
  src/file_operations_test.js
  src/markdown_generators.js
  src/markdown_generators_test.js
  test_data/courses/intentionally_left_empty.txt
  yarn.lock
Labels: waiting on author

#106 Convert videos to markdown, instead of relying on the hugo videogallery layout
  package.json
  src/file_operations_test.js
  src/markdown_generators.js
  src/markdown_generators_test.js
  test_data/courses/1-00-introduction-to-computers-and-engineering-problem-solving-spring-2012/bb55dad7f4888f0a1ad004600c5fb1f1_master.json
  test_data/courses/12-001-introduction-to-geology-fall-2013/d9aad1541f1a9d3c0f7b0dcf9531a9a1_master.json
  test_data/courses/2-00aj-exploring-sea-space-earth-fundamentals-of-engineering-design-spring-2009/e395587c58555f1fe564e8afd75899e6_master.json
  test_data/courses/3-00-thermodynamics-of-materials-fall-2002/93817ed85061287133ccbed5ccb752c9_master.json
  test_data/courses/ec-711-d-lab-energy-spring-2011/03ecfbe74faf55554e96b55bafa7899e_master.json
  yarn.lock
Labels: needs review

#107 Generate markdown for bottom text if it exists
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: waiting on author

#108 Increase timeout on file_operations tests
  src/file_operations_test.js
Labels: work in progress

#105 Remove logged error if the course is skipped and no course JSON is set
  src/file_operations.js
  src/file_operations_test.js
Labels: needs review

#110 fix embedded media nav bug
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: waiting on author
