Repository mitodl/ocw-to-hugo, pull requests merged in 2021-05, with the labels that each got.

#278 update a few npm packages to the latest version
  yarn.lock
Labels: needs review

#277 Add 11.405 to external link list
  src/external_links.json
Labels: needs review

#269 remove default salutation
  src/data_template_generators.js
  src/data_template_generators_test.js
Labels: needs review

#283 add lookup for other versions based on master subject
  src/file_operations.js
  src/file_operations_test.js
  src/markdown_generators.js
  src/markdown_generators_test.js
  test_data/courses/8-02x-physics-ii-electricity-magnetism-with-an-experimental-focus-spring-2005/8-02x-physics-ii-electricity-magnetism-with-an-experimental-focus-spring-2005_parsed.json
Labels: blocker, waiting on author

#279 display updated course numbers
  src/data_template_generators_test.js
  src/file_operations_test.js
  src/helpers.js
  test_data/courses/16-89j-space-systems-engineering-spring-2007/16-89j-space-systems-engineering-spring-2007_parsed.json
  test_data/courses/res-ec-001-exploring-fairness-in-machine-learning-for-international-development-spring-2020/res-ec-001-exploring-fairness-in-machine-learning-for-international-development-spring-2020_parsed.json
Labels: waiting on author

#292 move other_versions to course.json
  src/data_template_generators.js
  src/data_template_generators_test.js
  src/file_operations_test.js
  src/helpers.js
  src/markdown_generators.js
  src/markdown_generators_test.js
  test_data/courses/8-01sc-classical-mechanics-fall-2016/8-01sc-classical-mechanics-fall-2016_parsed.json
  test_data/courses/8-01x-physics-i-classical-mechanics-with-an-experimental-focus-fall-2002/8-01x-physics-i-classical-mechanics-with-an-experimental-focus-fall-2002_parsed.json
  test_data/courses/8-02-physics-ii-electricity-and-magnetism-spring-2007/8-02-physics-ii-electricity-and-magnetism-spring-2007_parsed.json
  test_data/courses/8-02x-physics-ii-electricity-magnetism-with-an-experimental-focus-spring-2005/8-02x-physics-ii-electricity-magnetism-with-an-experimental-focus-spring-2005_parsed.json
Labels: waiting on author

#290 Resolve legacy subtitle URLs
  src/helpers.js
  src/helpers_test.js
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: needs review

#296 open learning library
  src/data_template_generators.js
  src/data_template_generators_test.js
  src/helpers.js
Labels: waiting on author
