Repository mitodl/ocw-to-hugo, pull requests merged in 2021-04, with the labels that each got.

#244 Add course info links
  package.json
  src/data_template_generators.js
  src/data_template_generators_test.js
  src/helpers.js
  src/helpers_test.js
  src/markdown_generators_test.js
  yarn.lock
Labels: needs review

#246 popup video links
  src/file_operations_test.js
  src/helpers.js
  src/helpers_test.js
  src/markdown_generators.js
  test_data/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006_parsed.json
  test_data/courses/21g-107-chinese-i-streamlined-fall-2014/21g-107-chinese-i-streamlined-fall-2014_parsed.json
  test_data/courses/8-02-physics-ii-electricity-and-magnetism-spring-2007/8-02-physics-ii-electricity-and-magnetism-spring-2007_parsed.json
Labels: waiting on author

#252 video page baseurl
  src/helpers.js
  src/helpers_test.js
Labels: waiting on author

#249 use course_feature_tags
  src/data_template_generators.js
  src/data_template_generators_test.js
  src/file_operations.js
  src/file_operations_test.js
  src/helpers.js
  src/helpers_test.js
Labels: Blocked, waiting on author

#258 use salutation if it exists
  src/data_template_generators.js
  src/data_template_generators_test.js
  src/file_operations_test.js
  test_data/courses/res-ec-001-exploring-fairness-in-machine-learning-for-international-development-spring-2020/res-ec-001-exploring-fairness-in-machine-learning-for-international-development-spring-2020_parsed.json
Labels: waiting on author
