Repository mitodl/ocw-to-hugo, pull requests merged in 2021-08, with the labels that each got.

#320 add parent_uid to the front matter on sections that have a parent
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: blocker, needs review

#323 move course description to the course data template
  src/data_template_generators.js
  src/data_template_generators_test.js
  src/markdown_generators.js
Labels: needs review

#326 course description document relative urls
  src/constants.js
  src/helpers.js
  src/helpers_test.js
  src/markdown_generators.js
  src/turndown.js
Labels: waiting on author

#332 Remove course home page from markdown generation
  src/markdown_generators.js
  src/markdown_generators_test.js
Labels: needs review
